### ISSUE TITLE
Doesn't Work with latest version of ghost

### ISSUE THREAD

**Issue by tmli3b3rm4n** [sethlilly/Vapor#60]
`ERROR [2017-10-29 18:58:13] "POST /ghost/api/v0.1/themes/upload/" 422 276ms
NAME: ThemeValidationError
MESSAGE: Theme is not compatible or contains errors.
level:normal
[object Object]
ERROR DETAILS:
    fatal:    true
    level:    error
    rule:     Replace <code>{{pageUrl}}</code> with <code>{{page_url}}</code>
    details:  The helper <code>{{pageUrl}}</code> was replaced with <code>{{page_url}}</code>.<br>Find more information about the <code>{{page_url}}</code> helper <a href="https://themes.ghost.org/docs/page_url" target=_blank>here</a>.
    failures: 
      - 
        ref:     partials/pagination.hbs
        message: Please remove or replace {{pageUrl}} from this template
    code:     GS001-DEPR-PURL
ThemeValidationError: Theme is not compatible or contains errors.
    at ThemeValidationError.GhostError (/var/lib/ghost/versions/1.16.0/core/server/errors.js:9:26)
    at new ThemeValidationError (/var/lib/ghost/versions/1.16.0/core/server/errors.js:52:20)
    at resultHandler (/var/lib/ghost/versions/1.16.0/core/server/themes/validate.js:32:31)
    at tryCatcher (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/1.16.0/node_modules/gscan/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) `

**Comment by tmli3b3rm4n** [comment]
AH looks like you noted this.  I'll leave it open for anyone eles passing through.

**Comment by pokono** [comment]
I'm waiting for 2.0!!

**Comment by pascalandy** [comment]
With 229 folks who have forked this project, I'm sure we can find someone who adapt it for Ghost > 1.0 :-p

![screen shot 2018-03-31 at 5 32 33 pm](https://user-images.githubusercontent.com/6694151/38167773-a7b3313c-3509-11e8-866c-8b4887498739.jpg)

**Comment by pascalandy** [comment]
I just found https://github.com/robinj/gwei

**Comment by sethlilly** [comment]
Thank you @pokono! I've just merged this and released it as the 1.5 release!
